### PR TITLE
Create main.go

### PR DESCRIPTION
**Pull request by liam-quotabook**

### CODE REVIEW

**Comment by liam-quotabook** [comment]
hi

**Comment by liam-quotabook** [comment]
@olambdao sleep?

**Review by olambdao — APPROVED** [review]

**Comment by liam-quotabook** [comment]
asdf

**Comment by olambdao** [comment]
fdas

**Comment by olambdao** [comment]
@olambdao @liam-quotabook asdf

**Review by olambdao — APPROVED** [review]

**Comment by liam-quotabook** [comment]
@olambdao asdf

**Comment by liam-quotabook** [comment]
@olambdao fafa

**Pull request closed without merging**
